#ifndef RE2_CPP_RS_H
#define RE2_CPP_RS_H

#pragma once

/* Generated by cbindgen for re2-cpp-cabi. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

typedef struct Re2CppRegex {
  uint8_t _private[0];
} Re2CppRegex;

/**
 * Compiles a UTF-8 RE2 pattern and returns an owned regex handle.
 *
 * # Safety
 *
 * When `pattern_len` is nonzero, `pattern` must point to `pattern_len`
 * readable bytes for the duration of this call. The bytes must contain valid
 * UTF-8. The returned pointer must be released with `re2_cpp_rs_free`.
 */
struct Re2CppRegex *re2_cpp_rs_new(const uint8_t *pattern, size_t pattern_len);

/**
 * Frees a regex handle allocated by `re2_cpp_rs_new`.
 *
 * # Safety
 *
 * `ptr` must be null or a live pointer returned by `re2_cpp_rs_new`.
 * Passing any other pointer, or freeing the same pointer twice, is undefined
 * behavior.
 */
void re2_cpp_rs_free(struct Re2CppRegex *ptr);

/**
 * Runs RE2 partial matching against a live regex handle.
 *
 * # Safety
 *
 * `ptr` must be null or a live pointer returned by `re2_cpp_rs_new`. When
 * `text_len` is nonzero, `text` must point to `text_len` readable bytes.
 */
bool re2_cpp_rs_partial_match(const struct Re2CppRegex *ptr, const uint8_t *text, size_t text_len);

#endif /* RE2_CPP_RS_H */
