//! Generate `crates/qoi-rs/tests/golden_data.rs` — known-answer vectors produced by
//! the **reference C** (`qoi-sys`). The committed data file is pure bytes, so the
//! golden tests in `qoi-rs` run with no C toolchain present.
//!
//! Run with: `cargo run -p qoi-diff --example gen_golden`
use qoi_sys::{encode, Desc};
use std::fmt::Write as _;
use std::path::PathBuf;

struct Spec {
    name: &'static str,
    width: u32,
    height: u32,
    channels: u8,
    colorspace: u8,
}

/// Build a deterministic pixel buffer for a named pattern, chosen to exercise every
/// QOI opcode (RUN incl. the 62 boundary, INDEX, DIFF, LUMA, RGB, RGBA).
fn pixels_for(name: &str, w: u32, h: u32, channels: u8) -> Vec<u8> {
    let n = (w * h) as usize;
    let mut px = Vec::with_capacity(n * channels as usize);
    let mut lcg: u32 = 0xC0FF_EE11;
    let mut rng = move || {
        lcg = lcg.wrapping_mul(1664525).wrapping_add(1013904223);
        (lcg >> 24) as u8
    };
    for i in 0..n {
        let (r, g, b, a) = match name {
            // All identical -> long RUN, crossing the 62 boundary and end flush.
            "solid_rgb" | "solid_rgba" => (17, 34, 51, 200),
            // Small per-pixel steps -> DIFF then LUMA boundaries.
            "gradient" => {
                let v = (i % 200) as u8;
                (v, v.wrapping_add(3), v.wrapping_sub(5), 255)
            }
            // Few repeating colors -> INDEX hits.
            "indexed" => {
                let k = (i % 5) as u8;
                (k * 40, 255 - k * 40, 80 + k * 10, 255)
            }
            // Alpha varies -> RGBA chunks.
            "alpha" => {
                let v = (i % 64) as u8;
                (v, 128, 255 - v, (i % 256) as u8)
            }
            // Full noise -> mostly RGB/RGBA.
            _ => (rng(), rng(), rng(), rng()),
        };
        px.push(r);
        px.push(g);
        px.push(b);
        if channels == 4 {
            px.push(a);
        }
    }
    px
}

fn main() {
    let specs = [
        Spec {
            name: "one_px_rgb",
            width: 1,
            height: 1,
            channels: 3,
            colorspace: 0,
        },
        Spec {
            name: "one_px_rgba",
            width: 1,
            height: 1,
            channels: 4,
            colorspace: 1,
        },
        Spec {
            name: "solid_rgb",
            width: 100,
            height: 1,
            channels: 3,
            colorspace: 0,
        },
        Spec {
            name: "solid_rgba",
            width: 8,
            height: 9,
            channels: 4,
            colorspace: 0,
        },
        Spec {
            name: "gradient",
            width: 64,
            height: 4,
            channels: 3,
            colorspace: 0,
        },
        Spec {
            name: "gradient",
            width: 32,
            height: 3,
            channels: 4,
            colorspace: 1,
        },
        Spec {
            name: "indexed",
            width: 31,
            height: 3,
            channels: 4,
            colorspace: 0,
        },
        Spec {
            name: "alpha",
            width: 20,
            height: 5,
            channels: 4,
            colorspace: 0,
        },
        Spec {
            name: "noise",
            width: 23,
            height: 7,
            channels: 3,
            colorspace: 0,
        },
        Spec {
            name: "noise",
            width: 16,
            height: 16,
            channels: 4,
            colorspace: 1,
        },
    ];

    let mut out = String::new();
    out.push_str(
        "// AUTO-GENERATED by `cargo run -p qoi-diff --example gen_golden`. DO NOT EDIT.\n\
         // Known-answer vectors: `encoded` was produced by the reference C qoi_encode\n\
         // (vendor/qoi @ 97bacc86). The golden tests assert the safe port reproduces it.\n\n\
         pub struct Golden {\n    \
         pub name: &'static str,\n    \
         pub width: u32,\n    pub height: u32,\n    pub channels: u8,\n    pub colorspace: u8,\n    \
         pub pixels: &'static [u8],\n    pub encoded: &'static [u8],\n}\n\n\
         pub static GOLDEN: &[Golden] = &[\n",
    );

    let mut count = 0usize;
    for s in &specs {
        let pixels = pixels_for(s.name, s.width, s.height, s.channels);
        let desc = Desc {
            width: s.width,
            height: s.height,
            channels: s.channels,
            colorspace: s.colorspace,
        };
        let encoded = encode(&pixels, &desc).expect("reference encode failed");
        count += 1;

        write!(
            out,
            "    Golden {{ name: {:?}, width: {}, height: {}, channels: {}, colorspace: {},\n        pixels: &{:?},\n        encoded: &{:?} }},\n",
            format!("{}_{}x{}_c{}", s.name, s.width, s.height, s.channels),
            s.width, s.height, s.channels, s.colorspace, pixels, encoded
        )
        .unwrap();
    }
    out.push_str("];\n");

    let dest = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../qoi-rs/tests/golden_data.rs");
    std::fs::create_dir_all(dest.parent().unwrap()).unwrap();
    std::fs::write(&dest, out).unwrap();
    eprintln!("wrote {} golden vectors to {}", count, dest.display());
}
