/* Generated by cbindgen from qoi-cabi. The safe Rust QOI port, exposed over C. */

#ifndef QOI_RS_H
#define QOI_RS_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/*
 C-ABI image description (`#[repr(C)]`, fixed-width fields).
 */
typedef struct QoiRsDesc {
  /*
   Image width in pixels.
   */
  uint32_t width;
  /*
   Image height in pixels.
   */
  uint32_t height;
  /*
   Channels: 3 (RGB) or 4 (RGBA).
   */
  uint8_t channels;
  /*
   Colorspace: 0 (sRGB) or 1 (linear).
   */
  uint8_t colorspace;
} QoiRsDesc;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Encode raw pixels into a QOI stream.

 `data`/`data_len` describe the input (`width*height*channels` bytes). On success
 writes the output length to `*out_len` and returns a Rust-allocated buffer (free
 with [`qoi_rs_free`]); on failure sets `*out_len = 0` and returns `NULL`.

 # Safety
 `data` must point to `data_len` readable bytes (or be NULL), `desc` to a valid
 `QoiRsDesc`, and `out_len` to a writable `size_t`.
 */
uint8_t *qoi_rs_encode(const uint8_t *data,
                       uintptr_t data_len,
                       const struct QoiRsDesc *desc,
                       uintptr_t *out_len);

/*
 Decode a QOI stream into raw pixels.

 `channels` is 0 (use the header), 3, or 4. On success fills `*out_desc`, writes
 the pixel-buffer length to `*out_len`, and returns a Rust-allocated buffer (free
 with [`qoi_rs_free`]); on failure sets `*out_len = 0` and returns `NULL`.

 # Safety
 `data` must point to `data_len` readable bytes (or be NULL); `out_desc` and
 `out_len` must be writable.
 */
uint8_t *qoi_rs_decode(const uint8_t *data,
                       uintptr_t data_len,
                       struct QoiRsDesc *out_desc,
                       int channels,
                       uintptr_t *out_len);

/*
 Free a buffer returned by [`qoi_rs_encode`] or [`qoi_rs_decode`].

 `len` must be the length that call reported. A NULL pointer or zero length is a
 no-op.

 # Safety
 `ptr` must have come from one of this module's functions and not been freed
 already, with `len` the length it returned.
 */
void qoi_rs_free(uint8_t *ptr, uintptr_t len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* QOI_RS_H */
